CREATE TABLE t_token
(
  id SERIAL PRIMARY KEY,
  hash VARCHAR(50) NOT NULL
);

CREATE TABLE t_locale
(
  id SERIAL PRIMARY KEY,
  key VARCHAR(100) NOT NULL UNIQUE,
  value VARCHAR(500) NOT NULL
);

CREATE TABLE t_toggle
(
  id SERIAL PRIMARY KEY,
  key VARCHAR(100) NOT NULL UNIQUE,
  value BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE t_image
(
  id SERIAL PRIMARY KEY,
  key VARCHAR(100) NOT NULL UNIQUE,
  value VARCHAR(200) NOT NULL
);

CREATE TABLE t_html
(
  id SERIAL PRIMARY KEY,
  key VARCHAR(100) NOT NULL UNIQUE,
  value TEXT NOT NULL
);
